src/pages/partDetails/PartInfo/SelectField.tsx
src/pages/partDetails/PartInfo/TypeField.tsx
src/pages/partDetails/PartInfo/styles.ts
src/pages/partDetails/PartInfo/types.ts

fix: Warning: Received `false` for a non-boolean,
fixed it using [Transient props](https://styled-components.com/docs/api#transient-props)

fix: styled component prop warning

---

.guthub/pull_request_template.md

This branch will add a pull request template to make future ones more consistent and descriptive.

feat/#197/create pull_request_template.md

---

src/components/Button/Button.tsx
src/components/Button/styles.ts
src/components/PartCard/SearchInfoCompact.tsx
src/components/Upload/AddPartUpload.tsx
src/components/Upload/Upload.tsx
src/components/Upload/UploadMobile/AddPartUploadMobile.tsx
src/components/Upload/UploadMobile/UploadMobile.tsx
src/pages/addPart/addPartForm/AddPartForm.tsx
src/pages/addPart/batch/BatchForm.tsx
src/pages/addPart/check/CheckForm.tsx
src/pages/addPart/documentation/Upload.tsx
src/pages/addPart/recentlyAdded/RecentlyAdded.tsx
src/pages/admin/category/AddCategory.tsx
src/pages/admin/category/Categories.tsx
src/pages/admin/location/AddLocation.tsx
src/pages/admin/location/Locations.tsx
src/pages/admin/vendor/AddVendor.tsx
src/pages/admin/vendor/Vendors.tsx
src/pages/list/MakeList.tsx
src/pages/listDetails/ListDetails.tsx
src/pages/listDetails/phone/list/PhoneList.tsx
src/pages/partDetails/comments/Comments.tsx

Currently, button parameters are set where ever the buttons are implemented. We only want to be able to pick between a set number of variants. This pull request addresses this issue.
- add new variant prop to pass the button variant you want
- add new `buttonStyles` object that maps each variant to a style object
-   [x] **Linting**: Have you run the linter to ensure code consistency?
-   [x] **Code Formatting**: Is the code formatted according to project standards?

224 refactor button variants

---

src/pages/partDetails/handleApiRequestSnackbar.ts
src/pages/partDetails/hierarchy/ChildItemSelector.tsx
src/pages/partDetails/hierarchy/ParentItemSelector.tsx
src/pages/partDetails/hierarchy/index.tsx
src/pages/partDetails/hierarchy/styles.ts
src/pages/partDetails/partInfo/types.ts
src/utils/handleApiRequestSnackbar.ts

Currently, using state instead of react hook form when handling blur request
- using react hook form to handle api request 
- using a separate handler to handle snackbar api request
-   [x] **Linting**: Have you run the linter to ensure code consistency?
-   [x] **Code Formatting**: Is the code formatted according to project standards?

233 refactor using react hook form on hierarchy component

---

src/pages/partDetails/Log.tsx
src/pages/partDetails/hierarchy/ChildItemSelector.tsx
src/pages/partDetails/hierarchy/ParentItemSelector.tsx
src/pages/partDetails/partInfo/EditableField.tsx
src/pages/partDetails/partInfo/PartInfo.tsx
src/pages/partDetails/partInfo/SelectField.tsx
src/pages/partDetails/partInfo/hooks/useUpdatePartForm.tsx
src/pages/partDetails/partInfo/styles.ts
src/pages/partDetails/partInfo/types.ts
src/services/api.ts
src/services/apiTypes.ts
src/services/hooks/itemTemplates/useGetItemTemplateById.tsx
src/services/hooks/itemTemplates/useUpdateItemTemplate.tsx
src/services/hooks/items/useGetItemById.tsx
src/services/hooks/items/useIsWpIdUnique.tsx

Currently, code is not updated for new api endpoint.
- updated to use new endpoint
- added wp id field, with unique id check
- added new endpoints to api file
- fix spacing on fields

241 refactor update partinfo page using updated api properties

---

src/pages/search/Search.tsx
src/services/hooks/items/useGetItemsInfinite.tsx

- Need to fix the react query hook so that it works with the refactored API
- Need to fix bug when less than 10 item show up in a search
Currently, 
- Changed the react query hook so that it works with the refactored API by splicing the array of items
- Fixed the bug when less the 10 items show up in a search using conditions

refactored infinite scroll

---

src/App.tsx
src/style/GlobalStyles.ts

Currently, there is no MUI theme 
- add new mui theme

feat: add mui global theme to root

---

.eslintrc.cjs
package.json

Currently, the option `--fix` is run with lint which can cause bugs during the tests when pull requests are made
- remove the `--fix` option

fix: update configurations

---

src/pages/partDetails/partInfo/PartInfo.tsx

Currently, wp id is not updating
- removed check if field is edited to temp fix wp i field

fix: tempfix for wpid + spinner

---

package-lock.json
package.json
src/components/PartCard/PartCard.stories.tsx
src/components/PartCard/PartCard.tsx
src/components/PartCard/SearchInfo/SearchInfo.tsx
src/components/PartCard/SearchInfoCompact.tsx
src/pages/list/MakeList.tsx
src/pages/listDetails/ListDetails.tsx
src/services/apiTypes.ts
src/services/hooks/export/useExportToExcel.ts

Currently, there is a hook for this, but is not being used yet.
- changed the hook slightly.
- used the hook in list export button
- fixed some item template/item type issues
-   [ ] **Review**: Have you reviewed your own changes to ensure they align with best practices?

list can now be exported

---

.storybook/preview.tsx
src/components/CustomDialog/CustomDialog.stories.tsx
src/components/CustomDialog/CustomDialog.tsx
src/style/GlobalStyles.ts

Currently, there are no storybook for the dialog component
- Added a dialog storybook

291 feat dialog storybook

---

src/components/ItemCard/ItemCard.tsx
src/components/ItemCard/SearchInfo/SearchInfo.tsx
src/components/TopBar/HamburgerMenu/HamburgerMenu.tsx
src/components/TopBar/TopBar.tsx
src/components/TopBar/hooks/useNavigation.tsx
src/pages/addItem/hooks/useAddItemForm.tsx
src/pages/listDetails/ListDetails.tsx
src/pages/listDetails/phone/list/PhoneList.tsx
src/services/hooks/list/useGetListById.tsx

- currently the network gets back an undefined error request for getListById query.
- also fixing grammar on route name "makelist" to correct pathname "make-list" in search info,item card, and topbar component.
- fix extra error post request being made in addPart.
- added enabled:!!id to prevent it from being run on every new page/refresh.
- changed "makelist" to "make-list" in pathname.
- fixed unnecessary extra addItem post request that was being run but failing.

295 fix fix getlistbyid query

---

src/components/ListCard/ListCard.tsx

Fix custom dialog

---

src/components/TopBar/HamburgerMenu/HamburgerMenu.tsx
src/components/TopBar/ResponsiveAppBar.tsx
src/components/TopBar/styles.ts
src/pages/list/styles.ts
src/pages/search/styles.ts

Currently, hamburger menu was not displaying in phone mode/responsive mode
- added back hamburger menu.
- some CCS fixes for margins for search inputs.
- 

added back hamburger menu to phone

---

src/components/TopBar/ResponsiveAppBar.tsx
src/pages/addItem/addItemForm/FormContent.tsx
src/pages/addItem/recentlyAdded/RecentlyAdded.tsx
src/pages/list/MakeList.tsx
src/pages/login/styles.ts

Currently, there are some errors in the console
- added missing key in map (FormContent)
- removed missing image prop
- fixed: MUI: The Menu component doesn't accept a Fragment as a child.Consider providing an array instead.
- fixed: Unknown prop variant, styled component error, by swapping custom buttons to mui button

327 fix errors in log

---

src/pages/itemDetails/itemInfo/ItemInfo.tsx
src/services/api.ts
src/services/hooks/template/useGetItemTemplateById.ts
src/services/hooks/template/useGetItemTemplates.ts
src/services/hooks/template/useUpdateItemTemplate.ts

Currently, update template does not use updated by id, but api is updated so it is required now.
- updates template on item info using updated by id
- updated api service and hook
- updated query keys to match each other for template hooks

330 bug bad request when edit on part details

---

src/components/AddItemFormFields/Comment/Comment.tsx
src/components/AddItemFormFields/Revision/Revision.tsx
src/components/AddItemFormFields/SerialNumber/SerialNumber.tsx
src/components/AddItemFormFields/WpId/WpId.tsx
src/components/ItemCard/ItemCard.stories.tsx
src/components/ItemCard/SearchInfoCompact/SearchInfoCompact.stories.tsx
src/pages/addItem/addItemForm/FormContent.tsx
src/pages/addItem/hooks/itemValidator.ts
src/pages/addItem/hooks/useAddItemForm.ts
src/services/apiTypes.ts

Currently, there was no field to input the itemtemplate. revision.
-added revision component
- revision added to validator
- reivison added to form
- revision added to Item template api type
- minor styling changes

333 add revision input field

---

src/components/ItemDetails/CommentForm/CommentForm.tsx

Currently, there is a typo on submit button
- fixed typo on submit button.

fix: button text typo

---

src/App.tsx
src/components/AddItemFormFields/TemplateTypes/TemplateTypes.tsx
src/components/AddItemFormFields/styles.ts
src/components/AutocompleteSelect.tsx
src/components/FormInput.tsx
src/components/TopBar/HamburgerMenu/HamburgerMenu.tsx
src/components/TopBar/ResponsiveAppBar.tsx
src/components/TopBar/styles.ts
src/pages/admin/hooks/templateValidator.ts
src/pages/admin/hooks/useAddTemplateForm.ts
src/pages/admin/styles.ts
src/pages/admin/template/AddTemplate.tsx

Currently, there is no functionality to add a template
- a page to add template

168 add template in admin page

---

src/main.tsx

Currently, had react query devtools, but it has been unused for quite some time.
-removal of react query devtools in main.tsx

removal of query devtools

---

src/components/ItemDetails/Entry.tsx

Currently, log entry does not say who the change was made by.
- added first name and last name to log entry, so the user can tell who made the change

fix: missing name log entry

---

src/components/Upload/AddItemUpload.tsx
src/components/Upload/Upload.tsx
src/components/Upload/UploadMobile/UploadMobile.tsx
src/pages/addItem/batch/hooks/useBatchForm.tsx
src/pages/addItem/hooks/itemValidator.ts
src/pages/addItem/hooks/useAddItemForm.ts
src/services/api.ts
src/services/hooks/documents/useUploadDocumentToTemplate.ts

Added functionality for uploading files when adding items, and fixed a small wpid and serialnumber bug
- see commits

357 fix adding documents in add item flow
